### ISSUE TITLE
Add doc to wrap as collection

### ISSUE THREAD

**Issue by golngaz** [b2pweb/bdf-prime#38]
Adding doc to `->wrapAs('collection')` to get EntityCollection in `\Bdf\Prime\Query\ReadCommandInterface::wrapAs`

Like done on EntityCollection : `Bdf\Prime\Collection\EntityCollection.php::link`

**Comment by vincent4vx** [comment]
Done here : https://github.com/b2pweb/bdf-prime/wiki/Queries#projection-and-query-execution-result
